### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ss-iptv** [Eleven-am/frames#8]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle frames@0.1.0~presetup: frames@0.1.0
6 silly lifecycle frames@0.1.0~presetup: no script for presetup, continuing
7 info lifecycle frames@0.1.0~setup: frames@0.1.0
8 verbose lifecycle frames@0.1.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle frames@0.1.0~setup: PATH: /usr/share/npm/bin/node-gyp-bin:/home/frames/node_modul$
10 verbose lifecycle frames@0.1.0~setup: CWD: /home/frames
11 silly lifecycle frames@0.1.0~setup: Args: [ '-c',
11 silly lifecycle   'npm install && next build && pm2 start ecosystem.config.js' ]
12 silly lifecycle frames@0.1.0~setup: Returned: code: 1  signal: null
13 info lifecycle frames@0.1.0~setup: Failed to exec setup script
14 verbose stack Error: frames@0.1.0 setup: `npm install && next build && pm2 start ecosystem.config.$
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid frames@0.1.0
16 verbose cwd /home/frames
17 error Linux 5.4.0-1102-oracle
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "setup"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error frames@0.1.0 setup: `npm install && next build && pm2 start ecosystem.config.js`
22 error Exit status 1
23 error Failed at the frames@0.1.0 setup script 'npm install && next build && pm2 start ecosystem.co$
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the frames package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm install && next build && pm2 start ecosystem.config.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs frames
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls frames
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Eleven-am** [comment]
Have you tried reinstalling it in 2025. there is a docker image and a guide to follow if that helops
